### ISSUE TITLE
Media Manager Resource

### ISSUE THREAD

**Issue by brunosm16** [brunosm16/media-manager#3]
### To-do

Create a media manager resource and it's endpoints

### Endpoints

- [x] Create media in batch
- [x] Display file
- [x] Get medias by limit date
- [x] Get medias by dispositive

**Comment by brunosm16** [comment]
[Closed](https://github.com/brunosm16/media-manager/commit/b14e21be71bfffe7c05e88eb613223a7fd694444)
