### ISSUE TITLE
Retrieve Latest Medias

### ISSUE THREAD

**Issue by brunosm16** [brunosm16/media-manager#4]
### To-do 

- [x] Retrieve latest medias by a limit date provided on request 
- [x] Setup Github Actions for project
- [x] Implement a reusable logger for every request

**Comment by brunosm16** [comment]
[Close](https://github.com/brunosm16/media-manager/commit/4355d4906fd0b7cd8f90c60ced97cdd67ce9c255)
